# Uncomment the next line to define a global platform for your project
# platform :ios, '16.2'

target 'gc-auth-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gc-auth-ios
 pod 'PureCloudPlatformClientV2', :git => 'https://github.com/MyPureCloud/platform-client-sdk-ios.git', :tag => '136.0.1'

end
